### PR TITLE
Test actual hostname

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: Islandora-CLAW/CLAW#573

# What does this Pull Request do?

I realized that now more than ever we need to setup some functional tests as my getHost() was returning 
```
FINE: Using default anonymous (false) for GET/HEAD requests, host (StandardEngine[Catalina].StandardHost[localhost])
```

So this uses the `getRequestURL()` to get the actual URL you are requesting, then I match the starting to the Site URLs. 

This means you can allow anonymous for `http://localhost:8080/fcrepo` and force JWTs for `http://localhost:8080/manager/html`

This does a first match (as in the first URL that matches is used), which might not be the best. 

Also, we have no way to _not_ have Syn activated. So currently you must use a JWT to access the manager/html site.

Perhaps we should allow for a way to "disable" JWTs for a URL?

# What's new?

Really just using the public URL requested inside of the internal host designation.

# How should this be tested?

1. Build it and stick it in to claw_vagrant.
2. Add a line to your `/var/lib/tomcat8/conf/logging.properties` like `ca.islandora.syn.level = FINE`
3. Edit the provided `syn-settings.xml` to add another site like
```
<config version='1'>
    <site url="http://localhost:8080/manager/html" algorithm='RS256' encoding='PEM' path='/home/ubuntu/auth/public.key' default='false' anonymous='false'/>
    <site algorithm='RS256' encoding='PEM' path='/home/ubuntu/auth/public.key' default='true' anonymous='true'/>
    <token user='admin' roles='admin'>
        islandora
    </token>
</config>
```
4. Restart tomcat
5. Goto http://localhost:8080/fcrepo/rest and view Fedora
6. Goto http://localhost:8080/manager/html and get a 401 Unauthorized page

**Note**: If you add the role "manager-gui" to the static token, you can then access the `http://localhost:8080/manager/html`. But this seems less than favourable. Especially if people have other services running on Tomcat, but maybe this can be solved by making it into a ServletFilter? I saw @ajs6f & @jonathangreen chatting on IRC about that?

# Interested parties
@jonathangreen @ajs6f

### CODE REVIEW

**Comment by ajs6f** [comment]
One of the nice things about a servlet filter (vs. a Tomcat valve) is that it is specific to a particular URL-pattern, so it would meet the needs @whikloj outlines above.

I need to get on that. If someone will file me a ticket I will just do it in the next week or two (modulo changing $job).

**Comment by jonathangreen** [comment]
So you can constrain a valve to a particular container as well, claw vagrant is setting this up here:
https://github.com/Islandora-CLAW/claw_vagrant/blob/master/configs/Syn/web.xml#L47-L58

We could be applying this valve to just tomcat. I believe right now it will only apply to things with a security constraint, so for example blaze graph etc don't require tokens. In my initial testing none of them did, I did't specifically test the manger though. 

I agree with @ajs6f that this should probably be handled in container configuration, and I think it can be.

**Comment by ajs6f** [comment]
@jonathangreen : "this should probably be handled in container configuration"

That is definitely the real point. I agree that it can and should be.

**Comment by whikloj** [comment]
I'm happy with whatever doesn't over reach. My previous anonymous fix doesn't really work though as the URLs don't match, so it will always default to `default`.

But as for fixing the larger issue, we can hold on to that for now. I'll make a ticket for @ajs6f to work his magic on.

**Comment by ajs6f** [comment]
I have no objections and never did-- my comments were totally to future possibilities.

**Comment by whikloj** [comment]
I'm closing this in favour of my hopefully soon to complete Filter

**Pull request closed without merging**
